name 'wordpress'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures wordpress'
long_description 'Installs/Configures wordpress'
version '0.1.41'

depends 'yum', '~> 3.6.3'
depends 'apt', '~> 2.7.0'
depends 'mariadb', '~> 0.3.0'
depends 'mysql2_chef_gem', '~> 1.0.2'
depends 'database', '~> 4.0.7'
depends 'nginx', '~> 2.7.6'
depends 'php-fpm', '~> 0.7.4'
depends 'tar', '~> 0.7.0'